routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\UploadController;
use App\Http\Controllers\FriendsController;
use App\Http\Controllers\StatusesController;
use App\Http\Controllers\FriendshipsController;
use App\Http\Controllers\StatusLikesController;
use App\Http\Controllers\UsersStatusController;
use App\Http\Controllers\CommentLikesController;
use App\Http\Controllers\NotificationsController;
use App\Http\Controllers\StatusCommentsController;
use App\Http\Controllers\AcceptFriendshipsController;
use App\Http\Controllers\ReadNotificationsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route::get('/home', [HomeController::class, 'index'])->name('home'); */

Route::get('/', function () {
    return view('welcome');
});

/* Statuses */

Route::get('statuses', [StatusesController::class, 'index'])->name('statuses.index');
Route::get('statuses/{status}', [StatusesController::class, 'show'])->name('statuses.show');
Route::post('statuses', [StatusesController::class, 'store'])->name('statuses.store')->middleware('auth');

/* Likes */

Route::post('statuses/{status}/likes', [StatusLikesController::class, 'store'])->name('statuses.likes.store')->middleware('auth');
Route::delete('statuses/{status}/likes', [StatusLikesController::class, 'destroy'])->name('statuses.likes.destroy')->middleware('auth');

/* Comments */

Route::post('statuses/{status}/comments', [StatusCommentsController::class, 'store'])->name('statuses.comments.store')->middleware('auth');

/* Likes Comment */

Route::post('comments/{comment}/likes', [CommentLikesController::class, 'store'])->name('comments.likes.store')->middleware('auth');
Route::delete('comments/{comment}/likes', [CommentLikesController::class, 'destroy'])->name('comments.likes.destroy')->middleware('auth');

/* Users */

Route::get('@{user}', [UsersController::class, 'show'])->name('users.show');

/* Statuses Users */

Route::get('users/{user}/statuses', [UsersStatusController::class, 'index'])->name('users.statuses.index');

/* Friends */

Route::get('friends', [FriendsController::class, 'index'])->name('friends.index')->middleware('auth');

/* Friendships */
Route::get('friendships/{recipient}', [FriendshipsController::class, 'show'])->name('friendships.show')->middleware('auth');
Route::post('friendships/{recipient}', [FriendshipsController::class, 'store'])->name('friendships.store')->middleware('auth');
Route::delete('friendships/{user}', [FriendshipsController::class, 'destroy'])->name('friendship.destroy')->middleware('auth');

/* Accept Friendships */

Route::get('friends/requests', [AcceptFriendshipsController::class, 'index'])->name('accept-friendships.index')->middleware('auth');
Route::post('accept-friendships/{sender}', [AcceptFriendshipsController::class, 'store'])->name('accept-friendships.store')->middleware('auth');
Route::delete('accept-friendships/{sender}', [AcceptFriendshipsController::class, 'destroy'])->name('accept-friendships.destroy')->middleware('auth');

/* Notifications */

Route::get('notifications', [NotificationsController::class, 'index'])->name('notifications.index')->middleware('auth');

/* Read Notifications */

Route::post('read-notifications/{notification}', [ReadNotificationsController::class, 'store'])->name('read-notifications.store')->middleware('auth');
Route::delete('read-notifications/{notification}', [ReadNotificationsController::class, 'destroy'])->name('read-notifications.destroy')->middleware('auth');

/* Uploads */

Route::post('upload', [UploadController::class, 'store']);


/* Route::resource('comments', CommentController::class); */

Auth::routes();

app/Models/Comment.php
<?php

namespace App\Models;

use App\Models\User;
use App\Models\Status;
use App\Traits\HasLikes;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Comment extends Model
{
    use HasFactory;
    use HasLikes;

    /* protected $table = "comentarios"; */

    protected $fillable = [
        'user_id',
        'status_id',
        'body',
    ];

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function status(){
        return $this->belongsTo(Status::class);
    }

    public function path(){
        return route('statuses.show', $this->status_id) . '#comment-' . $this->id;
    }


}

resources/views/comments/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Comentarios</div>

                    <h1>Crear Comentario</h1></h1>

                    <form action="{{ route('comments.update', $comment->id) }}" method="post">
                        @csrf
                        @method('PUT')

                        <label for="">Comentario</label>
                        <textarea name="description" id="" cols="30" rows="10">{{ $comment->description }}</textarea>
                        <label for="">Likes</label>
                        <input type="text" name="likes" value= {{ $comment->likes }}>
                        <label for="">Dislikes</label>
                        <input type="text" name="dislikes" value= {{ $comment->dislikes }}>
                        <button type="submit">Guardar</button>
                    </form>

                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/comments/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="pull-left">
                        <div class="card-header">Comentarios</div>
                    </div>
                    <div class="pull-left p-2">
                        <a href="{{ route('comments.create') }}" class="btn btn-success"> Crear Nuevo Comentario</a>

                    </div>
                    <div class="p-3">
                        <h1>Comentarios</h1>
                        <table class="table table-bordered">
                            <thead>
                                <tr></tr>
                                    <th>ID</th>
                                    <th>Comentario</th>
                                    <th>Likes</th>
                                    <th>Dislikes</th>
                                    <th>Fecha</th>
                                    <th>Acciones</th>
                                </thead>
                                <tbody>
                                    @foreach($comments as $comment)
                                        <tr>
                                            <td>{{ $comment->id }}</td>
                                            <td>{{ $comment->description }}</td>
                                            <td>{{ $comment->likes }}</td>
                                            <td>{{ $comment->dislikes }}</td>
                                            <td>{{ $comment->created_at }}</td>
                                            <td>
                                                <form action="{{ route('comments.destroy', $comment->id) }}" method="post">

                                                    <a class = "btn btn-info" href="{{ route('comments.show', $comment->id) }}">Mostrar</a>
                                                    <a class = "btn btn-primary" href="{{ route('comments.edit', $comment->id) }}">Editar</a>

                                                    @csrf
                                                    @method('DELETE')
                                                    <button type='submit' class="btn btn-danger">Eliminar</button>
                                                </form>

                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/comments/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Comentario</div>

                <h1>Mostra Comentario</h1></h1>

                <p>Descripcion :</p> {{ $comment->description }}</p>
                <p>Likes :</p> {{ $comment->likes }}</p>
                <p>Dislikes :</p> {{ $comment->dislikes }}</p>

            </div>

            <a href="{{ route('comments.index') }}">Volver a Comentarios</a>
        </div>
    </div>
</div>

@endsection